# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEdgeColor <- function(m, colorTrue, colorFalse, colorDiff) {
    .Call('_multinets_getEdgeColor', PACKAGE = 'multinets', m, colorTrue, colorFalse, colorDiff)
}

iterateColor <- function(x, colorTrue, colorFalse) {
    .Call('_multinets_iterateColor', PACKAGE = 'multinets', x, colorTrue, colorFalse)
}

iterateShape <- function(x, shapeTrue, shapeFalse) {
    .Call('_multinets_iterateShape', PACKAGE = 'multinets', x, shapeTrue, shapeFalse)
}

openPlot <- function(A) {
    .Call('_multinets_openPlot', PACKAGE = 'multinets', A)
}

